name: Android Release Build

on:
  push:
    tags:
      - 'v*.*.*'   # Triggers on tags like v1.0.0, v2.3.4

jobs:
  build:
    name: Build and Release APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload Release to GitHub
      uses: softprops/action-gh-release@v2
      with:
        files: app/build/outputs/apk/debug/app-debug.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
